# See https://github.com/SeleniumHQ/docker-selenium#via-docker-compose
version: '3.3'
services:
  chrome:
    container_name: functional-tests_chrome_1
    image: selenium/node-chrome:3.141.59-20210713
    shm_size: '1gb'
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444

  hub:
    container_name: selenium_hub
    image: selenium/hub:3.141.59-20210713
    environment:
      GRID_DEBUG: "true"
      GRID_MAX_SESSION: 2
    ports:
     - "4444:4444"
    expose:
     - "4444"

  tests:
    container_name: functional-tests_tests_1
    build: .
    links:
      - hub
    volumes:
      - ./:/tests
      - /tests/node_modules
      - ./errorShots:/tests/errorShots
