/**
 * The AWS WAF web ACLs that protect NICE services, and the hostnames each one sits in front of.
 *
 * A web ACL issues its own integration URL for the AWS WAF JavaScript SDK, and that URL can't be
 * worked out from the hostname: the ids in it are generated by AWS. So this is a lookup table, with
 * one entry per web ACL rather than one per hostname. Hostnames that share a load balancer (or
 * CloudFront distribution) share a web ACL, and so share an entry.
 *
 * Each entry is:
 * - `hosts` - the exact hostnames served from behind the web ACL, e.g. `["www.nice.org.uk"]`. No
 *   wildcards, so list every hostname.
 * - `scriptURL` - the integration URL from 'Application integration' in the AWS WAF console. Ops are
 *   issuing the 'Intelligent threat integration' one, which ends in `challenge.js`, e.g.
 *   `https://<id>.eu-west-1.sdk.awswaf.com/<id>/<id>/challenge.js`. The 'CAPTCHA integration' one
 *   ends in `jsapi.js` and would work just the same; both put `AwsWafIntegration` on `window`.
 *   Leave it empty and the entry does nothing, so hostnames can be listed before their web ACL exists.
 * - `cookieDomains` - optional, e.g. `[".nice.org.uk"]`. Widens the `aws-waf-token` cookie from the
 *   exact host so one token works across subdomains. Only set this once the same domain is on the
 *   web ACL's token domain list, otherwise AWS rejects every token we ask it for.
 *
 * A hostname that isn't listed gets no script, which is what we want for localhost and for any
 * environment with no web ACL in front of it.
 *
 * The entries below are ops' official list of which hostnames sit behind which web ACL, as of
 * 2026-10-08. When ops add a hostname or rotate a URL, change it here and release.
 *
 * @see https://docs.aws.amazon.com/waf/latest/developerguide/waf-js-challenge-api.html
 */

const cookieDomains = [".nice.org.uk"];

export const integrations = [
	// web ACL sandbox (nextweb-sandbox1).
	{
		hosts: ["nextweb.sandbox1-ds.net"],
		scriptURL:
			"https://e92f72f6da93.eu-west-1.sdk.awswaf.com/e92f72f6da93/6169085d0d0b/challenge.js",
		cookieDomains: [".sandbox1-ds.net"],
	},

	// Live. One web ACL fronts the main site, BNF, BNFC, CKS and indev. The bare nice.org.uk
	// redirects to www, so it's left out: no page ever renders there.
	{
		hosts: [
			"www.nice.org.uk",
			"bnf.nice.org.uk",
			"bnfc.nice.org.uk",
			"cks.nice.org.uk",
			"indev.nice.org.uk",
		],
		scriptURL:
			"https://ddbd340a0652.eu-west-1.sdk.awswaf.com/ddbd340a0652/1d47535b626c/challenge.js",
		cookieDomains,
	},

	// Alpha, beta, test and dev environments behind the shared pre-production web ACL
	{
		hosts: [
			// Alpha
			"alpha.nice.org.uk",
			"alpha-arms.nice.org.uk",
			"alpha-scheduler.nice.org.uk",
			"alpha-timelines.nice.org.uk",
			"alpha-docgen.nice.org.uk",
			"alpha-perfdash.nice.org.uk",
			"alpha-identityadmin.nice.org.uk",
			"alpha-identityapi.nice.org.uk",
			"alpha-indev.nice.org.uk",
			"alpha.indev.nice.org.uk",
			"alpha-api.nice.org.uk",
			"alpha-monitoring.nice.org.uk",
			"alpha-next-web-api.nice.org.uk",
			"alpha-publications.nice.org.uk",
			"alpha-next-feature.nice.org.uk",

			// Beta
			"beta.nice.org.uk",
			"beta-appraisals.nice.org.uk",
			"beta-accounts.nice.org.uk",
			"beta-docs.nice.org.uk",
			"beta-perfdash.nice.org.uk",
			"beta-publications.nice.org.uk",
			"beta.publications.nice.org.uk",
			"beta.openathens.nice.org.uk",
			"beta-openathens.nice.org.uk",
			"beta-identityapi.nice.org.uk",
			"beta-identityadmin.nice.org.uk",
			"beta-monitoring.nice.org.uk",
			"beta-next-web-api.nice.org.uk",
			"beta-indev.nice.org.uk",
			"beta.indev.nice.org.uk",
			"beta-docsupply.nice.org.uk",
			"beta-api.nice.org.uk",
			"beta-bnf.nice.org.uk",
			"beta-bnfc.nice.org.uk",
			"beta-cks.nice.org.uk",

			// Test
			"test.nice.org.uk",
			"test-next-feature.nice.org.uk",
			"test-indev.nice.org.uk",
			"test-publications.nice.org.uk",
			"test-monitoring.nice.org.uk",
			"test-reviewer.nice.org.uk",
			"test-accounts.nice.org.uk",
			"test-bnf.nice.org.uk",
			"test-bnfc.nice.org.uk",
			"test-cks.nice.org.uk",

			// Dev
			"dev.nice.org.uk",
			"dev-indev.nice.org.uk",
			"dev-monitoring.nice.org.uk",

			// Shared / special
			"ping-logger.nice.org.uk",
			"aslive-publications.nice.org.uk",
		],
		scriptURL:
			"https://ddbd340a0652.eu-west-1.sdk.awswaf.com/ddbd340a0652/9435ee08f314/challenge.js",
		cookieDomains,
	},
];
