/**
 * The AWS WAF web ACLs that protect NICE services, and the hostnames each one sits in front of.
 *
 * A web ACL issues its own integration URL for the AWS WAF JavaScript SDK, and that URL can't be
 * worked out from the hostname: the ids in it are generated by AWS. So this is a lookup table, with
 * one entry per web ACL rather than one per hostname. Hostnames that share a load balancer (or
 * CloudFront distribution) share a web ACL, and so share an entry.
 *
 * Each entry is:
 * - `hosts` - the exact hostnames served from behind the web ACL, e.g. `["www.nice.org.uk"]`. No
 *   wildcards, so list every hostname.
 * - `scriptURL` - the integration URL from 'Application integration' in the AWS WAF console. Ops are
 *   issuing the 'Intelligent threat integration' one, which ends in `challenge.js`, e.g.
 *   `https://<id>.eu-west-1.sdk.awswaf.com/<id>/<id>/challenge.js`. The 'CAPTCHA integration' one
 *   ends in `jsapi.js` and would work just the same; both put `AwsWafIntegration` on `window`.
 *   Leave it empty and the entry does nothing, so hostnames can be listed before their web ACL exists.
 * - `cookieDomains` - optional, e.g. `[".nice.org.uk"]`. Widens the `aws-waf-token` cookie from the
 *   exact host so one token works across subdomains. Only set this once the same domain is on the
 *   web ACL's token domain list, otherwise AWS rejects every token we ask it for.
 *
 * A hostname that isn't listed gets no script, which is what we want for localhost and for any
 * environment with no web ACL in front of it.
 *
 * ! The hostnames below were grouped by which ones resolved to the same address in DNS on
 * ! 2026-10-01, on the basis that a shared address means a shared load balancer. That's a starting
 * ! point, not the truth: confirm the grouping with ops when they hand over each script URL, and
 * ! merge or split entries to match the web ACLs they actually create. Every URL is empty until then.
 *
 * @see https://docs.aws.amazon.com/waf/latest/developerguide/waf-js-challenge-api.html
 */

const cookieDomains = [".nice.org.uk"];

export const integrations = [
	// web ACL sandbox (nextweb-sandbox1).
	{
		hosts: ["nextweb.sandbox1-ds.net"],
		scriptURL:
			"https://e92f72f6da93.eu-west-1.sdk.awswaf.com/e92f72f6da93/6169085d0d0b/challenge.js",
		cookieDomains: [".sandbox1-ds.net"],
	},

	// Live. Main site's load balancer fronts next-web, guidance-web, consultations and the
	// niceorg backend, so they're all covered by this one entry. The bare nice.org.uk redirects to
	// www and is served from a different address, so it's left out: no page ever renders there.
	{
		hosts: ["www.nice.org.uk"],
		scriptURL: "",
		cookieDomains,
	},
	{
		hosts: ["bnf.nice.org.uk"],
		scriptURL: "",
		cookieDomains,
	},
	{
		hosts: ["bnfc.nice.org.uk"],
		scriptURL: "",
		cookieDomains,
	},
	{
		hosts: ["cks.nice.org.uk"],
		scriptURL: "",
		cookieDomains,
	},
	{
		hosts: ["indev.nice.org.uk"],
		scriptURL: "",
		cookieDomains,
	},

	// Alpha
	{
		hosts: [
			"alpha.nice.org.uk",
			"alpha-indev.nice.org.uk",
			"alpha-monitoring.nice.org.uk",
			"alpha-publications.nice.org.uk",
		],
		scriptURL: "",
		cookieDomains,
	},

	// Beta
	{
		hosts: ["beta.nice.org.uk", "beta-monitoring.nice.org.uk"],
		scriptURL: "",
		cookieDomains,
	},
	{
		hosts: ["beta-indev.nice.org.uk"],
		scriptURL: "",
		cookieDomains,
	},
	{
		hosts: ["beta-publications.nice.org.uk"],
		scriptURL: "",
		cookieDomains,
	},
	{
		hosts: ["beta-bnf.nice.org.uk"],
		scriptURL: "",
		cookieDomains,
	},
	{
		hosts: ["beta-bnfc.nice.org.uk"],
		scriptURL: "",
		cookieDomains,
	},
	{
		hosts: ["beta-cks.nice.org.uk"],
		scriptURL: "",
		cookieDomains,
	},

	// Test and dev. The main site, indev and publications on test resolve to the same address as
	// the main site and indev on dev, so they look to share one load balancer
	{
		hosts: [
			"test.nice.org.uk",
			"test-indev.nice.org.uk",
			"test-publications.nice.org.uk",
			"dev.nice.org.uk",
			"dev-indev.nice.org.uk",
		],
		scriptURL: "",
		cookieDomains,
	},
	{
		hosts: ["test-monitoring.nice.org.uk"],
		scriptURL: "",
		cookieDomains,
	},
	{
		hosts: ["dev-monitoring.nice.org.uk"],
		scriptURL: "",
		cookieDomains,
	},
	{
		hosts: ["test-bnf.nice.org.uk"],
		scriptURL: "",
		cookieDomains,
	},
	{
		hosts: ["test-bnfc.nice.org.uk"],
		scriptURL: "",
		cookieDomains,
	},
	{
		hosts: ["test-cks.nice.org.uk"],
		scriptURL: "",
		cookieDomains,
	},
];
